# Generated by Django 2.1.3 on 2019-03-08 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helper', '0002_auto_20190308_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Helper',
        ),
    ]
