# Generated by Django 2.1.3 on 2019-03-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_auto_20190308_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='author',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='content',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='title',
        ),
    ]
